### ISSUE TITLE
[Feature Request] Add glowing effect only visible by team members

### ISSUE THREAD

**Issue by elhertz** [beabfc/teamcmd#1]
It'd be nice to be able to see your team members all the time thanks to the glowing effect. 
Could this be configured so only team members can see this effect? also add a way so you can toggle it personally without affecting other members' settings.
Something like `/t set glowing true`

**Comment by beabfc** [comment]
I don't have the time to implement this at the moment but will happily review any pull request.

**Comment by beabfc** [comment]
I don't think this would be possible without adding client-side logic. You can create a separate mod to achieve this functionality. If the other mod also uses scoreboard teams, it'll be compatible to this one. Closing as a wontfix.
